[2024-10-25T14:29:08.221+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-10-25T14:23:00+00:00 [queued]>
[2024-10-25T14:29:08.240+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-10-25T14:23:00+00:00 [queued]>
[2024-10-25T14:29:08.241+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-10-25T14:29:08.274+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): run_bot_notebook> on 2024-10-25 14:23:00+00:00
[2024-10-25T14:29:08.278+0000] {standard_task_runner.py:57} INFO - Started process 21534 to run task
[2024-10-25T14:29:08.280+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bot_dag', 'run_bot_notebook', 'scheduled__2024-10-25T14:23:00+00:00', '--job-id', '4152', '--raw', '--subdir', 'DAGS_FOLDER/bot_dag.py', '--cfg-path', '/tmp/tmpxskmdze3']
[2024-10-25T14:29:08.283+0000] {standard_task_runner.py:85} INFO - Job 4152: Subtask run_bot_notebook
[2024-10-25T14:29:08.369+0000] {task_command.py:410} INFO - Running <TaskInstance: bot_dag.run_bot_notebook scheduled__2024-10-25T14:23:00+00:00 [running]> on host 454d1fc6eddf
[2024-10-25T14:29:08.522+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bot_dag' AIRFLOW_CTX_TASK_ID='run_bot_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-10-25T14:23:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-25T14:23:00+00:00'
[2024-10-25T14:29:08.523+0000] {bot_dag.py:9} INFO - Функция run_bot_notebook запущена
[2024-10-25T14:29:08.585+0000] {bot_dag.py:22} ERROR - Ошибка при запуске скрипта: python: can't open file '/src/pbot.py': [Errno 2] No such file or directory

[2024-10-25T14:29:08.586+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-10-25T14:29:08.603+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=bot_dag, task_id=run_bot_notebook, execution_date=20241025T142300, start_date=20241025T142908, end_date=20241025T142908
[2024-10-25T14:29:08.626+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-10-25T14:29:08.646+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
