[2024-11-04T13:45:40.825+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-11-02T16:50:00+00:00 [queued]>
[2024-11-04T13:45:40.841+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-11-02T16:50:00+00:00 [queued]>
[2024-11-04T13:45:40.842+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-11-04T13:45:40.862+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): run_bot_notebook> on 2024-11-02 16:50:00+00:00
[2024-11-04T13:45:40.867+0000] {standard_task_runner.py:57} INFO - Started process 16414 to run task
[2024-11-04T13:45:40.870+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bot_dag', 'run_bot_notebook', 'scheduled__2024-11-02T16:50:00+00:00', '--job-id', '15828', '--raw', '--subdir', 'DAGS_FOLDER/bot_dag.py', '--cfg-path', '/tmp/tmpu_kl6wq2']
[2024-11-04T13:45:40.872+0000] {standard_task_runner.py:85} INFO - Job 15828: Subtask run_bot_notebook
[2024-11-04T13:45:40.975+0000] {task_command.py:410} INFO - Running <TaskInstance: bot_dag.run_bot_notebook scheduled__2024-11-02T16:50:00+00:00 [running]> on host 454d1fc6eddf
[2024-11-04T13:45:41.108+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bot_dag' AIRFLOW_CTX_TASK_ID='run_bot_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T16:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-02T16:50:00+00:00'
[2024-11-04T13:45:41.109+0000] {bot_dag.py:9} INFO - Функция run_bot_notebook запущена
[2024-11-04T13:45:41.190+0000] {bot_dag.py:22} ERROR - Ошибка при запуске скрипта: python: can't open file '/src/pbot.py': [Errno 2] No such file or directory

[2024-11-04T13:45:41.191+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-11-04T13:45:41.203+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=bot_dag, task_id=run_bot_notebook, execution_date=20241102T165000, start_date=20241104T134540, end_date=20241104T134541
[2024-11-04T13:45:41.221+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-11-04T13:45:41.237+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
