[2024-10-23T10:27:40.735+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-10-23T09:33:00+00:00 [queued]>
[2024-10-23T10:27:40.741+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-10-23T09:33:00+00:00 [queued]>
[2024-10-23T10:27:40.741+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-10-23T10:27:40.752+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): run_bot_notebook> on 2024-10-23 09:33:00+00:00
[2024-10-23T10:27:40.756+0000] {standard_task_runner.py:57} INFO - Started process 2068 to run task
[2024-10-23T10:27:40.758+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bot_dag', 'run_bot_notebook', 'scheduled__2024-10-23T09:33:00+00:00', '--job-id', '949', '--raw', '--subdir', 'DAGS_FOLDER/bot_dag.py', '--cfg-path', '/tmp/tmpgor38pu_']
[2024-10-23T10:27:40.762+0000] {standard_task_runner.py:85} INFO - Job 949: Subtask run_bot_notebook
[2024-10-23T10:27:40.801+0000] {task_command.py:410} INFO - Running <TaskInstance: bot_dag.run_bot_notebook scheduled__2024-10-23T09:33:00+00:00 [running]> on host 6ad8f4ca419c
[2024-10-23T10:27:40.867+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bot_dag' AIRFLOW_CTX_TASK_ID='run_bot_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T09:33:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T09:33:00+00:00'
[2024-10-23T10:27:40.868+0000] {bot_dag.py:9} INFO - Функция run_bot_notebook запущена
[2024-10-23T10:27:40.926+0000] {bot_dag.py:21} ERROR - Ошибка при запуске скрипта: python: can't open file '/app/pbot.py': [Errno 2] No such file or directory

[2024-10-23T10:27:40.926+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-10-23T10:27:40.935+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=bot_dag, task_id=run_bot_notebook, execution_date=20241023T093300, start_date=20241023T102740, end_date=20241023T102740
[2024-10-23T10:27:40.935+0000] {bot_dag.py:47} INFO - Задача выполнена успешно
[2024-10-23T10:27:40.977+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-10-23T10:27:40.992+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
