[2024-11-04T14:01:53.262+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-11-04T07:28:00+00:00 [queued]>
[2024-11-04T14:01:53.273+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-11-04T07:28:00+00:00 [queued]>
[2024-11-04T14:01:53.276+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-11-04T14:01:53.309+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): run_bot_notebook> on 2024-11-04 07:28:00+00:00
[2024-11-04T14:01:53.314+0000] {standard_task_runner.py:57} INFO - Started process 23532 to run task
[2024-11-04T14:01:53.318+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bot_dag', 'run_bot_notebook', 'scheduled__2024-11-04T07:28:00+00:00', '--job-id', '18146', '--raw', '--subdir', 'DAGS_FOLDER/bot_dag.py', '--cfg-path', '/tmp/tmp1u7i47hu']
[2024-11-04T14:01:53.319+0000] {standard_task_runner.py:85} INFO - Job 18146: Subtask run_bot_notebook
[2024-11-04T14:01:53.482+0000] {task_command.py:410} INFO - Running <TaskInstance: bot_dag.run_bot_notebook scheduled__2024-11-04T07:28:00+00:00 [running]> on host 454d1fc6eddf
[2024-11-04T14:01:53.848+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bot_dag' AIRFLOW_CTX_TASK_ID='run_bot_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T07:28:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-04T07:28:00+00:00'
[2024-11-04T14:01:53.849+0000] {bot_dag.py:9} INFO - Функция run_bot_notebook запущена
[2024-11-04T14:01:53.955+0000] {bot_dag.py:22} ERROR - Ошибка при запуске скрипта: python: can't open file '/src/pbot.py': [Errno 2] No such file or directory

[2024-11-04T14:01:53.956+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-11-04T14:01:54.000+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=bot_dag, task_id=run_bot_notebook, execution_date=20241104T072800, start_date=20241104T140153, end_date=20241104T140154
[2024-11-04T14:01:54.120+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-11-04T14:01:54.171+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
