[2024-10-23T14:51:00.492+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-10-23T13:06:00+00:00 [queued]>
[2024-10-23T14:51:00.511+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-10-23T13:06:00+00:00 [queued]>
[2024-10-23T14:51:00.512+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-10-23T14:51:00.575+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): run_bot_notebook> on 2024-10-23 13:06:00+00:00
[2024-10-23T14:51:00.578+0000] {standard_task_runner.py:57} INFO - Started process 179 to run task
[2024-10-23T14:51:00.596+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bot_dag', 'run_bot_notebook', 'scheduled__2024-10-23T13:06:00+00:00', '--job-id', '1187', '--raw', '--subdir', 'DAGS_FOLDER/bot_dag.py', '--cfg-path', '/tmp/tmpj76v3hoz']
[2024-10-23T14:51:00.602+0000] {standard_task_runner.py:85} INFO - Job 1187: Subtask run_bot_notebook
[2024-10-23T14:51:00.929+0000] {task_command.py:410} INFO - Running <TaskInstance: bot_dag.run_bot_notebook scheduled__2024-10-23T13:06:00+00:00 [running]> on host 454d1fc6eddf
[2024-10-23T14:51:01.456+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bot_dag' AIRFLOW_CTX_TASK_ID='run_bot_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T13:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T13:06:00+00:00'
[2024-10-23T14:51:01.467+0000] {bot_dag.py:9} INFO - Функция run_bot_notebook запущена
[2024-10-23T14:51:01.620+0000] {bot_dag.py:22} ERROR - Ошибка при запуске скрипта: python: can't open file '/src/pbot.py': [Errno 2] No such file or directory

[2024-10-23T14:51:01.625+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-10-23T14:51:01.691+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=bot_dag, task_id=run_bot_notebook, execution_date=20241023T130600, start_date=20241023T145100, end_date=20241023T145101
[2024-10-23T14:51:02.042+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-10-23T14:51:02.219+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
