[2024-11-04T13:59:47.609+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-11-04T02:27:00+00:00 [queued]>
[2024-11-04T13:59:47.618+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-11-04T02:27:00+00:00 [queued]>
[2024-11-04T13:59:47.619+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-11-04T13:59:47.637+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): run_bot_notebook> on 2024-11-04 02:27:00+00:00
[2024-11-04T13:59:47.644+0000] {standard_task_runner.py:57} INFO - Started process 22610 to run task
[2024-11-04T13:59:47.647+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bot_dag', 'run_bot_notebook', 'scheduled__2024-11-04T02:27:00+00:00', '--job-id', '17845', '--raw', '--subdir', 'DAGS_FOLDER/bot_dag.py', '--cfg-path', '/tmp/tmpiqg84c0s']
[2024-11-04T13:59:47.650+0000] {standard_task_runner.py:85} INFO - Job 17845: Subtask run_bot_notebook
[2024-11-04T13:59:47.786+0000] {task_command.py:410} INFO - Running <TaskInstance: bot_dag.run_bot_notebook scheduled__2024-11-04T02:27:00+00:00 [running]> on host 454d1fc6eddf
[2024-11-04T13:59:48.100+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bot_dag' AIRFLOW_CTX_TASK_ID='run_bot_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T02:27:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-04T02:27:00+00:00'
[2024-11-04T13:59:48.101+0000] {bot_dag.py:9} INFO - Функция run_bot_notebook запущена
[2024-11-04T13:59:48.183+0000] {bot_dag.py:22} ERROR - Ошибка при запуске скрипта: python: can't open file '/src/pbot.py': [Errno 2] No such file or directory

[2024-11-04T13:59:48.184+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-11-04T13:59:48.260+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=bot_dag, task_id=run_bot_notebook, execution_date=20241104T022700, start_date=20241104T135947, end_date=20241104T135948
[2024-11-04T13:59:48.337+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-11-04T13:59:48.434+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
