[2024-11-04T13:05:45.135+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-10-30T05:15:00+00:00 [queued]>
[2024-11-04T13:05:45.163+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-10-30T05:15:00+00:00 [queued]>
[2024-11-04T13:05:45.165+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-11-04T13:05:45.195+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): run_bot_notebook> on 2024-10-30 05:15:00+00:00
[2024-11-04T13:05:45.199+0000] {standard_task_runner.py:57} INFO - Started process 978 to run task
[2024-11-04T13:05:45.201+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bot_dag', 'run_bot_notebook', 'scheduled__2024-10-30T05:15:00+00:00', '--job-id', '10813', '--raw', '--subdir', 'DAGS_FOLDER/bot_dag.py', '--cfg-path', '/tmp/tmp6ndguw32']
[2024-11-04T13:05:45.204+0000] {standard_task_runner.py:85} INFO - Job 10813: Subtask run_bot_notebook
[2024-11-04T13:05:45.338+0000] {task_command.py:410} INFO - Running <TaskInstance: bot_dag.run_bot_notebook scheduled__2024-10-30T05:15:00+00:00 [running]> on host 454d1fc6eddf
[2024-11-04T13:05:45.757+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bot_dag' AIRFLOW_CTX_TASK_ID='run_bot_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T05:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-30T05:15:00+00:00'
[2024-11-04T13:05:45.759+0000] {bot_dag.py:9} INFO - Функция run_bot_notebook запущена
[2024-11-04T13:05:45.949+0000] {bot_dag.py:22} ERROR - Ошибка при запуске скрипта: python: can't open file '/src/pbot.py': [Errno 2] No such file or directory

[2024-11-04T13:05:45.950+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-11-04T13:05:46.067+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=bot_dag, task_id=run_bot_notebook, execution_date=20241030T051500, start_date=20241104T130545, end_date=20241104T130546
[2024-11-04T13:05:46.257+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-11-04T13:05:46.428+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
