[2025-01-15T14:09:31.893+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-11-04T15:57:00+00:00 [queued]>
[2025-01-15T14:09:31.899+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-11-04T15:57:00+00:00 [queued]>
[2025-01-15T14:09:31.899+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2025-01-15T14:09:31.909+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): run_bot_notebook> on 2024-11-04 15:57:00+00:00
[2025-01-15T14:09:31.912+0000] {standard_task_runner.py:57} INFO - Started process 184 to run task
[2025-01-15T14:09:31.914+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bot_dag', 'run_bot_notebook', 'scheduled__2024-11-04T15:57:00+00:00', '--job-id', '18687', '--raw', '--subdir', 'DAGS_FOLDER/bot_dag.py', '--cfg-path', '/tmp/tmpxur7w5_1']
[2025-01-15T14:09:31.916+0000] {standard_task_runner.py:85} INFO - Job 18687: Subtask run_bot_notebook
[2025-01-15T14:09:31.951+0000] {task_command.py:410} INFO - Running <TaskInstance: bot_dag.run_bot_notebook scheduled__2024-11-04T15:57:00+00:00 [running]> on host 53eafeeb4635
[2025-01-15T14:09:32.028+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bot_dag' AIRFLOW_CTX_TASK_ID='run_bot_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T15:57:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-04T15:57:00+00:00'
[2025-01-15T14:09:32.029+0000] {bot_dag.py:11} INFO - Функция run_ запущена
[2025-01-15T14:09:35.307+0000] {logging_mixin.py:149} INFO - Сообщение отправлено в канал: Чем безупречнее человек снаружи, тем больше демонов у него внутри…
[2025-01-15T14:09:35.308+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-01-15T14:09:35.320+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=bot_dag, task_id=run_bot_notebook, execution_date=20241104T155700, start_date=20250115T140931, end_date=20250115T140935
[2025-01-15T14:09:35.352+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-01-15T14:09:35.367+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
