[2025-01-15T14:34:00.835+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2025-01-15T14:33:00+00:00 [queued]>
[2025-01-15T14:34:00.840+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2025-01-15T14:33:00+00:00 [queued]>
[2025-01-15T14:34:00.840+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-01-15T14:34:00.847+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): run_bot_notebook> on 2025-01-15 14:33:00+00:00
[2025-01-15T14:34:00.849+0000] {standard_task_runner.py:57} INFO - Started process 327 to run task
[2025-01-15T14:34:00.851+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bot_dag', 'run_bot_notebook', 'scheduled__2025-01-15T14:33:00+00:00', '--job-id', '18701', '--raw', '--subdir', 'DAGS_FOLDER/bot_dag.py', '--cfg-path', '/tmp/tmpozxw6q6k']
[2025-01-15T14:34:00.852+0000] {standard_task_runner.py:85} INFO - Job 18701: Subtask run_bot_notebook
[2025-01-15T14:34:00.886+0000] {task_command.py:410} INFO - Running <TaskInstance: bot_dag.run_bot_notebook scheduled__2025-01-15T14:33:00+00:00 [running]> on host 75942bad379e
[2025-01-15T14:34:00.947+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bot_dag' AIRFLOW_CTX_TASK_ID='run_bot_notebook' AIRFLOW_CTX_EXECUTION_DATE='2025-01-15T14:33:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-15T14:33:00+00:00'
[2025-01-15T14:34:00.947+0000] {bot_dag.py:11} INFO - Функция run_ запущена
[2025-01-15T14:34:02.275+0000] {logging_mixin.py:149} INFO - Сообщение отправлено в канал: Всякий раз, когда человек допускает глупость, он делает это из самых благородных побуждений.
[2025-01-15T14:34:02.276+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-01-15T14:34:02.288+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=bot_dag, task_id=run_bot_notebook, execution_date=20250115T143300, start_date=20250115T143400, end_date=20250115T143402
[2025-01-15T14:34:02.338+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-01-15T14:34:02.351+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
