[2024-11-04T13:32:45.021+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-11-01T12:47:00+00:00 [queued]>
[2024-11-04T13:32:45.047+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bot_dag.run_bot_notebook scheduled__2024-11-01T12:47:00+00:00 [queued]>
[2024-11-04T13:32:45.048+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-11-04T13:32:45.078+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): run_bot_notebook> on 2024-11-01 12:47:00+00:00
[2024-11-04T13:32:45.083+0000] {standard_task_runner.py:57} INFO - Started process 11237 to run task
[2024-11-04T13:32:45.088+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bot_dag', 'run_bot_notebook', 'scheduled__2024-11-01T12:47:00+00:00', '--job-id', '14145', '--raw', '--subdir', 'DAGS_FOLDER/bot_dag.py', '--cfg-path', '/tmp/tmpp5sgpjpt']
[2024-11-04T13:32:45.091+0000] {standard_task_runner.py:85} INFO - Job 14145: Subtask run_bot_notebook
[2024-11-04T13:32:45.276+0000] {task_command.py:410} INFO - Running <TaskInstance: bot_dag.run_bot_notebook scheduled__2024-11-01T12:47:00+00:00 [running]> on host 454d1fc6eddf
[2024-11-04T13:32:45.531+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bot_dag' AIRFLOW_CTX_TASK_ID='run_bot_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T12:47:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-01T12:47:00+00:00'
[2024-11-04T13:32:45.532+0000] {bot_dag.py:9} INFO - Функция run_bot_notebook запущена
[2024-11-04T13:32:45.660+0000] {bot_dag.py:22} ERROR - Ошибка при запуске скрипта: python: can't open file '/src/pbot.py': [Errno 2] No such file or directory

[2024-11-04T13:32:45.661+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-11-04T13:32:45.684+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=bot_dag, task_id=run_bot_notebook, execution_date=20241101T124700, start_date=20241104T133245, end_date=20241104T133245
[2024-11-04T13:32:45.732+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-11-04T13:32:45.767+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
