[2024-10-23T08:04:30.222+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telegram_bot_dag.run_bot_notebook scheduled__2024-10-23T07:59:00+00:00 [queued]>
[2024-10-23T08:04:30.228+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telegram_bot_dag.run_bot_notebook scheduled__2024-10-23T07:59:00+00:00 [queued]>
[2024-10-23T08:04:30.228+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-10-23T08:04:30.237+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): run_bot_notebook> on 2024-10-23 07:59:00+00:00
[2024-10-23T08:04:30.244+0000] {standard_task_runner.py:57} INFO - Started process 3188 to run task
[2024-10-23T08:04:30.247+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'telegram_bot_dag', 'run_bot_notebook', 'scheduled__2024-10-23T07:59:00+00:00', '--job-id', '478', '--raw', '--subdir', 'DAGS_FOLDER/bot_dag.py', '--cfg-path', '/tmp/tmpfavvber2']
[2024-10-23T08:04:30.250+0000] {standard_task_runner.py:85} INFO - Job 478: Subtask run_bot_notebook
[2024-10-23T08:04:30.316+0000] {task_command.py:410} INFO - Running <TaskInstance: telegram_bot_dag.run_bot_notebook scheduled__2024-10-23T07:59:00+00:00 [running]> on host 5d6769ab5933
[2024-10-23T08:04:30.394+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='telegram_bot_dag' AIRFLOW_CTX_TASK_ID='run_bot_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T07:59:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T07:59:00+00:00'
[2024-10-23T08:04:30.397+0000] {bot_dag.py:11} INFO - Функция run_bot_notebook запущена
[2024-10-23T08:04:30.450+0000] {bot_dag.py:21} ERROR - Ошибка при запуске скрипта: python: can't open file '/Users/klovak_stefan/post_bot/src/pbot.py': [Errno 2] No such file or directory

[2024-10-23T08:04:30.452+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-10-23T08:04:30.462+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=telegram_bot_dag, task_id=run_bot_notebook, execution_date=20241023T075900, start_date=20241023T080430, end_date=20241023T080430
[2024-10-23T08:04:30.512+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-10-23T08:04:30.526+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
